# Every possible CLI should be in this file.
#
# Please use a plausible value, besu has to at least be able to parse it.
# If it is a multi-valued CLI make it a TOML array.
# If it is a number or boolean make it a number or boolean
# All other config options are strings, and must be quoted.

# Node Information
# Customizar
genesis-file="/opt/besu/genesis.json"
node-private-key-file="/opt/besu/nodeKey"
data-path="/opt/besu/data"

logging="INFO"

min-gas-price=0
api-gas-price-max=0
miner-enabled=false

# P2P network
p2p-enabled=true
discovery-enabled=true
static-nodes-file="/opt/besu/static-nodes.json"
p2p-host="0.0.0.0"
p2p-port=30303
max-peers=25
remote-connections-limit-enabled=false
host-allowlist=["*"]

# JSON-RPC
rpc-http-api=["DEBUG", "ETH", "ADMIN", "WEB3", "QBFT", "NET", "PERM", "TXPOOL", "PLUGINS", "TRACE"]
rpc-http-host="0.0.0.0"
rpc-http-cors-origins=["*"]
rpc-http-enabled=true
rpc-http-port=8545
rpc-http-max-active-connections=2000


# GRAPHQL-RPC
graphql-http-enabled=true
graphql-http-host="0.0.0.0"
graphql-http-port=8547
graphql-http-cors-origins=["*"]

# WebSockets API
rpc-ws-enabled=true
rpc-ws-host="0.0.0.0"
rpc-ws-port=8546
rpc-ws-api=["DEBUG", "ETH", "ADMIN", "WEB3", "QBFT", "NET", "PERM", "TXPOOL", "PLUGINS", "TRACE"]
rpc-ws-authentication-enabled=false

# Metrics
metrics-enabled=true
metrics-host="0.0.0.0"
metrics-port=9545


# permissions
permissions-nodes-config-file-enabled=true
permissions-nodes-config-file="/opt/besu/permissions_config.toml"


