version: '3.9'
name: blockscout
services:
  redis-db:
    container_name: blockscout-redis-db
    extends:
      file: ./services/redis.yml
      service: redis-db

  db-init:
    container_name: blockscout-db-init
    extends:
      file: ./services/db.yml
      service: db-init

  db:
    container_name: blockscout-db
    depends_on:
      db-init:
        condition: service_completed_successfully
    extends:
      file: ./services/db.yml
      service: db

  backend:
    container_name: blockscout-backend
    depends_on:
      - db
      - redis-db
    extends:
      file: ./services/backend.yml
      service: backend
    links:
      - db:database
    environment:
        ETHEREUM_JSONRPC_VARIANT: 'geth'
        ETHEREUM_JSONRPC_WS_URL: ws://host.docker.internal:7545
        INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER: 'true'
        INDEXER_INTERNAL_TRANSACTIONS_TRACER_TYPE: 'opcode'
        CHAIN_ID: '381660001'

  visualizer:
    container_name: blockscout-visualizer
    extends:
      file: ./services/visualizer.yml
      service: visualizer

  sig-provider:
    container_name: blockscout-sig-provider
    extends:
      file: ./services/sig-provider.yml
      service: sig-provider

  frontend:
    container_name: blockscout-frontend
    depends_on:
      - backend
    extends:
      file: ./services/frontend.yml
      service: frontend
    environment:
      NEXT_PUBLIC_NETWORK_ID: '381660001'
      NEXT_PUBLIC_NETWORK_RPC_URL: ws://host.docker.internal:7545

  stats-db-init:
    container_name: blockscout-stats-db-init
    extends:
      file: ./services/stats.yml
      service: stats-db-init

  stats-db:
    container_name: blockscout-stats-db
    depends_on:
      stats-db-init:
        condition: service_completed_successfully
    extends:
      file: ./services/stats.yml
      service: stats-db

  stats:
    container_name: blockscout-stats
    depends_on:
      - stats-db
      - backend
    extends:
      file: ./services/stats.yml
      service: stats

  user-ops-indexer:
    container_name: blockscout-user-ops-indexer
    depends_on:
      - db
      - backend
    extends:
      file: ./services/user-ops-indexer.yml
      service: user-ops-indexer

  proxy:
    container_name: blockscout-proxy
    depends_on:
      - backend
      - frontend
      - stats
    extends:
      file: ./services/nginx.yml
      service: proxy
