server:
  port: 8545
  address: 0.0.0.0
backend:
  chainId: 2021
  url: http://besu:8545
fileWallet:
  path: /data/keystore
  filenames:
    primaryExt: .toml
  metadata:
    keyFileProperty: '{{ index .signing "key-file" }}'
    passwordFileProperty: '{{ index .signing "password-file" }}'
log:
  level: debug
