admin:
  address: 0.0.0.0
  enabled: true
  port: 5101
  publicURL: http://127.0.0.1:5101
data-path: /mnt/d/Repo/GitHub/sandbox-firefly-besu-bacen-drex/sandbox-firefly-besu-bacen-drex/node/data
debug:
  port: 6060
discovery-enabled: true
event:
  dbevents:
    bufferSize: 10000
genesis-file: /mnt/d/Repo/GitHub/sandbox-firefly-besu-bacen-drex/sandbox-firefly-besu-bacen-drex/node/genesis.json
graphql-http-cors-origins:
- '*'
graphql-http-enabled: true
graphql-http-host: 0.0.0.0
graphql-http-port: 8547
host-allowlist:
- '*'
http:
  address: 0.0.0.0
  port: 5000
  publicURL: http://127.0.0.1:5000
identity: <função-participante-sequencial>
log:
  level: debug
logging: INFO
max-peers: 25
metrics: {}
metrics-enabled: true
metrics-host: 0.0.0.0
metrics-port: 9545
min-gas-price: 0
namespaces:
  default: default
  predefined:
  - defaultKey: 0xf4c6f7292724902a1ac96b6d4e2b246dbd94b28d
    description: Default predefined namespace
    multiparty:
      contract:
      - firstEvent: "0"
        location:
          address: 0xd3fc57ffd7b39461d55e597bf93b05f7809683e3
        options: {}
      enabled: true
      node:
        name: node_030dbb
      org:
        key: 0xf4c6f7292724902a1ac96b6d4e2b246dbd94b28d
        name: org_030dbb
    name: default
    plugins:
    - database0
    - blockchain0
    - dataexchange0
    - sharedstorage0
    - erc20_erc721
nat-method: NONE
p2p-enabled: true
p2p-port: 30303
permissions-accounts-contract-address: 0xb3f31049dADf7Ab0239afc2f04568CB19543044D
permissions-accounts-contract-enabled: true
permissions-nodes-contract-address: "0x0000000000000000000000000000000000009999"
permissions-nodes-contract-enabled: true
permissions-nodes-contract-version: 2
plugins:
  blockchain:
  - ethereum:
      ethconnect:
        topic: "0"
        url: http://evmconnect_0:5008
    name: blockchain0
    type: ethereum
  database:
  - name: database0
    sqlite3:
      migrations:
        auto: true
      url: /etc/firefly/data/db/sqlite.db?_busy_timeout=5000
    type: sqlite3
  dataexchange:
  - ffdx:
      url: http://dataexchange_0:3000
    name: dataexchange0
    type: ffdx
  sharedstorage:
  - ipfs:
      api:
        url: http://ipfs_0:5001
      gateway:
        url: http://ipfs_0:8080
    name: sharedstorage0
    type: ipfs
  tokens:
  - fftokens:
      url: http://tokens_0_0:3000
    name: erc20_erc721
    type: fftokens
remote-connections-limit-enabled: false
revert-reason-enabled: true
rpc-http-api:
- DEBUG
- ETH
- ADMIN
- WEB3
- QBFT
- NET
- PERM
- TXPOOL
- PLUGINS
- MINER
- TRACE
rpc-http-cors-origins:
- '*'
rpc-http-enabled: true
rpc-http-max-active-connections: 2000
rpc-ws-api:
- DEBUG
- ETH
- ADMIN
- WEB3
- QBFT
- NET
- PERM
- TXPOOL
- PLUGINS
- MINER
- TRACE
rpc-ws-authentication-enabled: true
rpc-ws-enabled: true
rpc-ws-host: 0.0.0.0
rpc-ws-port: 8546
spi:
  address: 0.0.0.0
  enabled: true
  port: 5101
  publicURL: http://127.0.0.1:5101
tx-pool: sequenced
tx-pool-limit-by-account-percentage: 1
tx-pool-max-size: 2500
tx-pool-retention-hours: 1
ui:
  path: ./frontend
