# Every possible CLI should be in this file.
#
# Please use a plausible value, besu has to at least be able to parse it.
# If it is a multi-valued CLI make it a TOML array.
# If it is a number or boolean make it a number or boolean
# All other config options are strings, and must be quoted.

# Node Information
# Customizar
data-path="/data"
genesis-file="/config/genesis.json"
revert-reason-enabled=true
identity="<função-participante-sequencial>"

genesis-file="/config/genesis.json"
node-private-key-file="/data/nodeKey"

logging="INFO"

# DOCKER | KUBERNETES | AUTO | NONE
# Customizar
nat-method="KUBERNETES"

min-gas-price=0

# Transaction Pool
tx-pool="sequenced"   
tx-pool-retention-hours=1   
tx-pool-limit-by-account-percentage=1   
tx-pool-max-size=2500

# P2P network
p2p-enabled=true
discovery-enabled=true
#p2p-host="0.0.0.0"
p2p-port=30303
max-peers=25
remote-connections-limit-enabled=false
host-allowlist=["*"]

# JSON-RPC
rpc-http-api=["DEBUG", "ETH", "ADMIN", "WEB3", "QBFT", "NET", "PERM", "TXPOOL", "PLUGINS", "MINER", "TRACE"]
rpc-http-cors-origins=["*"]
rpc-http-enabled=true
rpc-http-max-active-connections=2000
#rpc-http-authentication-enabled=true
#rpc-http-authentication-credentials-file="/etc/auth/auth.toml"

# GRAPHQL-RPC
graphql-http-enabled=true
graphql-http-host="0.0.0.0"
graphql-http-port=8547
graphql-http-cors-origins=["*"]

# WebSockets API
rpc-ws-enabled=true
rpc-ws-host="0.0.0.0"
rpc-ws-port=8546
rpc-ws-api=["DEBUG", "ETH", "ADMIN", "WEB3", "QBFT", "NET", "PERM", "TXPOOL", "PLUGINS", "MINER", "TRACE"]
rpc-ws-authentication-enabled=true

# Metrics
metrics-enabled=true
metrics-host="0.0.0.0"
metrics-port=9545

# Permissioning (utilizar esses paramêtros para habilitar a permissão)
permissions-nodes-contract-enabled=true
permissions-nodes-contract-address="0x0000000000000000000000000000000000009999"
permissions-nodes-contract-version=2
permissions-accounts-contract-enabled=true
permissions-accounts-contract-address="0xb3f31049dADf7Ab0239afc2f04568CB19543044D"

# permissions
#permissions-nodes-config-file-enabled=true
#permissions-nodes-config-file="/config/permissions_config.toml"

# bootnodes
#bootnodes=["enode://c25a5f3a08b6100b6ca5147abab6d5f233a5dbd82cb7f7c76a7d54ab377833e456f6480a38845454fd8d16dc622baa1c474ae2e8fc9bf679bb9b83c577b57a40@172.16.239.10:30303"]


# Discovery at boot is set to a list of static files, but will also discover new nodes should they be added
# static nodes
#static-nodes-file="/config/static-nodes.json"
#discovery-enabled=true
