# Every possible CLI should be in this file.
#
# Please use a plausible value, besu has to at least be able to parse it.
# If it is a multi-valued CLI make it a TOML array.
# If it is a number or boolean make it a number or boolean
# All other config options are strings, and must be quoted.

# Node Information
# Customizar
genesis-file="/opt/besu/genesis.json"
node-private-key-file="/opt/besu/nodeKey"
data-path="/data"
revert-reason-enabled=true

logging="INFO"

# DOCKER | KUBERNETES | AUTO | NONE
# Customizar
nat-method="AUTO"

min-gas-price=0

# Transaction Pool
#tx-pool="sequenced"   
#tx-pool-retention-hours=1   
#tx-pool-limit-by-account-percentage=1   
#tx-pool-max-size=2500

# P2P network
p2p-enabled=true
discovery-enabled=false
static-nodes-file="/opt/besu/static-nodes.json"
p2p-host="0.0.0.0"
p2p-port=30303
max-peers=25
remote-connections-limit-enabled=false
host-allowlist=["*"]

# JSON-RPC
rpc-http-api=["DEBUG", "ETH", "ADMIN", "WEB3", "QBFT", "NET", "PERM", "TXPOOL", "PLUGINS", "MINER", "TRACE"]
rpc-http-cors-origins=["*"]
rpc-http-enabled=true
rpc-http-host="0.0.0.0"
rpc-http-port=8545
rpc-http-max-active-connections=2000
#rpc-http-authentication-enabled=true
#rpc-http-authentication-credentials-file="/etc/auth/auth.toml"

# GRAPHQL-RPC
graphql-http-enabled=true
graphql-http-host="0.0.0.0"
graphql-http-port=8547
graphql-http-cors-origins=["*"]

# WebSockets API
rpc-ws-enabled=true
rpc-ws-host="0.0.0.0"
rpc-ws-port=8546
rpc-ws-api=["DEBUG", "ETH", "ADMIN", "WEB3", "QBFT", "NET", "PERM", "TXPOOL", "PLUGINS", "MINER", "TRACE"]
rpc-ws-authentication-enabled=false

# Metrics
metrics-enabled=true
metrics-host="0.0.0.0"
metrics-port=9545

# permissions
permissions-nodes-config-file-enabled=true
permissions-nodes-config-file="/opt/besu/permissions_config.toml"

# bootnodes
bootnodes=["enode://c73adda80f0f5f202c8f3e152a32ed8f00a7b88cb7c4bda3883313d3cfd69e3f2f1090b233202aab4299fe3a46dd8812a8c073799404389c7bc29d7c366dc675@172.16.239.10:30303"]

